package com.sxxa.hjjczz.dao;

import com.sxxa.hjjczz.entity.THjjczzSbsx;
import com.sxxa.hjjczz.entity.THjjczzSbsxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface THjjczzSbsxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int countByExample(THjjczzSbsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int deleteByExample(THjjczzSbsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int insert(THjjczzSbsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int insertSelective(THjjczzSbsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    List<THjjczzSbsx> selectByExample(THjjczzSbsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") THjjczzSbsx record, @Param("example") THjjczzSbsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_sbsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int updateByExample(@Param("record") THjjczzSbsx record, @Param("example") THjjczzSbsxExample example);
}