package com.sxxa.hjjczz.dao;

import com.sxxa.hjjczz.entity.THjjczzSnsx;
import com.sxxa.hjjczz.entity.THjjczzSnsxExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface THjjczzSnsxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int countByExample(THjjczzSnsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int deleteByExample(THjjczzSnsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int insert(THjjczzSnsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int insertSelective(THjjczzSnsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    List<THjjczzSnsx> selectByExample(THjjczzSnsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") THjjczzSnsx record, @Param("example") THjjczzSnsxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_snsx
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    int updateByExample(@Param("record") THjjczzSnsx record, @Param("example") THjjczzSnsxExample example);
}