package com.sxxa.hjjczz.dao;

import com.sxxa.hjjczz.entity.THjjczzZbfgzs;
import com.sxxa.hjjczz.entity.THjjczzZbfgzsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface THjjczzZbfgzsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int countByExample(THjjczzZbfgzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int deleteByExample(THjjczzZbfgzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int insert(THjjczzZbfgzs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int insertSelective(THjjczzZbfgzs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    List<THjjczzZbfgzs> selectByExample(THjjczzZbfgzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") THjjczzZbfgzs record, @Param("example") THjjczzZbfgzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_zbfgzs
     *
     * @mbggenerated Thu Mar 11 10:41:29 CST 2021
     */
    int updateByExample(@Param("record") THjjczzZbfgzs record, @Param("example") THjjczzZbfgzsExample example);
}