package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzFormslistField implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_formslist_field.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String zdmcEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String zdmcZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_formslist_field.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_formslist_field
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_formslist_field.XH
     *
     * @return the value of t_hjjczz_formslist_field.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_formslist_field.XH
     *
     * @param xh the value for t_hjjczz_formslist_field.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_formslist_field.TABLENAME
     *
     * @return the value of t_hjjczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_formslist_field.TABLENAME
     *
     * @param tablename the value for t_hjjczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_formslist_field.ZDMC_EN
     *
     * @return the value of t_hjjczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getZdmcEn() {
        return zdmcEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_formslist_field.ZDMC_EN
     *
     * @param zdmcEn the value for t_hjjczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZdmcEn(String zdmcEn) {
        this.zdmcEn = zdmcEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_formslist_field.ZDMC_ZH
     *
     * @return the value of t_hjjczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getZdmcZh() {
        return zdmcZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_formslist_field.ZDMC_ZH
     *
     * @param zdmcZh the value for t_hjjczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZdmcZh(String zdmcZh) {
        this.zdmcZh = zdmcZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_formslist_field.TYPE
     *
     * @return the value of t_hjjczz_formslist_field.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_formslist_field.TYPE
     *
     * @param type the value for t_hjjczz_formslist_field.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}