package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzTdxpzs extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.ID
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.QD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double qd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.ZD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double zd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.ZHD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double zhd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.TDXPZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double tdxpz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.TDXPGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double tdxpgyhxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.XZWLYDDPGDMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double xzwlyddpgdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double tdxpzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdxpzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_tdxpzs
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.ID
     *
     * @return the value of t_hjjczz_tdxpzs.ID
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.ID
     *
     * @param id the value for t_hjjczz_tdxpzs.ID
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.XZQMC
     *
     * @return the value of t_hjjczz_tdxpzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_tdxpzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.XZQDM
     *
     * @return the value of t_hjjczz_tdxpzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_tdxpzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.MJ
     *
     * @return the value of t_hjjczz_tdxpzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.MJ
     *
     * @param mj the value for t_hjjczz_tdxpzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.QD
     *
     * @return the value of t_hjjczz_tdxpzs.QD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getQd() {
        return qd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.QD
     *
     * @param qd the value for t_hjjczz_tdxpzs.QD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setQd(Double qd) {
        this.qd = qd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.ZD
     *
     * @return the value of t_hjjczz_tdxpzs.ZD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getZd() {
        return zd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.ZD
     *
     * @param zd the value for t_hjjczz_tdxpzs.ZD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZd(Double zd) {
        this.zd = zd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.ZHD
     *
     * @return the value of t_hjjczz_tdxpzs.ZHD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getZhd() {
        return zhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.ZHD
     *
     * @param zhd the value for t_hjjczz_tdxpzs.ZHD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZhd(Double zhd) {
        this.zhd = zhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.TDXPZ
     *
     * @return the value of t_hjjczz_tdxpzs.TDXPZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getTdxpz() {
        return tdxpz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.TDXPZ
     *
     * @param tdxpz the value for t_hjjczz_tdxpzs.TDXPZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdxpz(Double tdxpz) {
        this.tdxpz = tdxpz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.TDXPGYHXS
     *
     * @return the value of t_hjjczz_tdxpzs.TDXPGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getTdxpgyhxs() {
        return tdxpgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.TDXPGYHXS
     *
     * @param tdxpgyhxs the value for t_hjjczz_tdxpzs.TDXPGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdxpgyhxs(Double tdxpgyhxs) {
        this.tdxpgyhxs = tdxpgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.XZWLYDDPGDMJ
     *
     * @return the value of t_hjjczz_tdxpzs.XZWLYDDPGDMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getXzwlyddpgdmj() {
        return xzwlyddpgdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.XZWLYDDPGDMJ
     *
     * @param xzwlyddpgdmj the value for t_hjjczz_tdxpzs.XZWLYDDPGDMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzwlyddpgdmj(Double xzwlyddpgdmj) {
        this.xzwlyddpgdmj = xzwlyddpgdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.TDXPZS
     *
     * @return the value of t_hjjczz_tdxpzs.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getTdxpzs() {
        return tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.TDXPZS
     *
     * @param tdxpzs the value for t_hjjczz_tdxpzs.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdxpzs(Double tdxpzs) {
        this.tdxpzs = tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.YEAR
     *
     * @return the value of t_hjjczz_tdxpzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.YEAR
     *
     * @param year the value for t_hjjczz_tdxpzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdxpzs.TYPE
     *
     * @return the value of t_hjjczz_tdxpzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdxpzs.TYPE
     *
     * @param type the value for t_hjjczz_tdxpzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}