package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzGdp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.GDP
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double gdp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.GDPZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String gdpzb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_gdp.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_gdp
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.XH
     *
     * @return the value of t_hjjczz_gdp.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.XH
     *
     * @param xh the value for t_hjjczz_gdp.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.XZQMC
     *
     * @return the value of t_hjjczz_gdp.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_gdp.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.XZQDM
     *
     * @return the value of t_hjjczz_gdp.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_gdp.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.GDP
     *
     * @return the value of t_hjjczz_gdp.GDP
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getGdp() {
        return gdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.GDP
     *
     * @param gdp the value for t_hjjczz_gdp.GDP
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setGdp(Double gdp) {
        this.gdp = gdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.GDPZB
     *
     * @return the value of t_hjjczz_gdp.GDPZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getGdpzb() {
        return gdpzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.GDPZB
     *
     * @param gdpzb the value for t_hjjczz_gdp.GDPZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setGdpzb(String gdpzb) {
        this.gdpzb = gdpzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.YEAR
     *
     * @return the value of t_hjjczz_gdp.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.YEAR
     *
     * @param year the value for t_hjjczz_gdp.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_gdp.TYPE
     *
     * @return the value of t_hjjczz_gdp.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_gdp.TYPE
     *
     * @param type the value for t_hjjczz_gdp.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}