package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzWrfhzs extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.NJSL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double njsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.CODPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double codpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.CODXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double codxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.ADPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double adpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.ADXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double adxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.EYHLPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double eyhlpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.EYHLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double eyhlxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.YFCPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double yfcpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.YFCXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double yfcxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.DYHWPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double dyhwpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.DYHWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double dyhwxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.GTFQWDQL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double gtfqwdql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.GTFWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double gtfwxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double wrfhzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wrfhzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.XH
     *
     * @return the value of t_hjjczz_wrfhzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.XH
     *
     * @param xh the value for t_hjjczz_wrfhzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.XZQMC
     *
     * @return the value of t_hjjczz_wrfhzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_wrfhzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.XZQDM
     *
     * @return the value of t_hjjczz_wrfhzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_wrfhzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.MJ
     *
     * @return the value of t_hjjczz_wrfhzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.MJ
     *
     * @param mj the value for t_hjjczz_wrfhzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.NJSL
     *
     * @return the value of t_hjjczz_wrfhzs.NJSL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getNjsl() {
        return njsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.NJSL
     *
     * @param njsl the value for t_hjjczz_wrfhzs.NJSL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setNjsl(Double njsl) {
        this.njsl = njsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.CODPFL
     *
     * @return the value of t_hjjczz_wrfhzs.CODPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getCodpfl() {
        return codpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.CODPFL
     *
     * @param codpfl the value for t_hjjczz_wrfhzs.CODPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setCodpfl(Double codpfl) {
        this.codpfl = codpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.CODXS
     *
     * @return the value of t_hjjczz_wrfhzs.CODXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getCodxs() {
        return codxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.CODXS
     *
     * @param codxs the value for t_hjjczz_wrfhzs.CODXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setCodxs(Double codxs) {
        this.codxs = codxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.ADPFL
     *
     * @return the value of t_hjjczz_wrfhzs.ADPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getAdpfl() {
        return adpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.ADPFL
     *
     * @param adpfl the value for t_hjjczz_wrfhzs.ADPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setAdpfl(Double adpfl) {
        this.adpfl = adpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.ADXS
     *
     * @return the value of t_hjjczz_wrfhzs.ADXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getAdxs() {
        return adxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.ADXS
     *
     * @param adxs the value for t_hjjczz_wrfhzs.ADXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setAdxs(Double adxs) {
        this.adxs = adxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.EYHLPFL
     *
     * @return the value of t_hjjczz_wrfhzs.EYHLPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getEyhlpfl() {
        return eyhlpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.EYHLPFL
     *
     * @param eyhlpfl the value for t_hjjczz_wrfhzs.EYHLPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setEyhlpfl(Double eyhlpfl) {
        this.eyhlpfl = eyhlpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.EYHLXS
     *
     * @return the value of t_hjjczz_wrfhzs.EYHLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getEyhlxs() {
        return eyhlxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.EYHLXS
     *
     * @param eyhlxs the value for t_hjjczz_wrfhzs.EYHLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setEyhlxs(Double eyhlxs) {
        this.eyhlxs = eyhlxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.YFCPFL
     *
     * @return the value of t_hjjczz_wrfhzs.YFCPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getYfcpfl() {
        return yfcpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.YFCPFL
     *
     * @param yfcpfl the value for t_hjjczz_wrfhzs.YFCPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYfcpfl(Double yfcpfl) {
        this.yfcpfl = yfcpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.YFCXS
     *
     * @return the value of t_hjjczz_wrfhzs.YFCXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getYfcxs() {
        return yfcxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.YFCXS
     *
     * @param yfcxs the value for t_hjjczz_wrfhzs.YFCXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYfcxs(Double yfcxs) {
        this.yfcxs = yfcxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.DYHWPFL
     *
     * @return the value of t_hjjczz_wrfhzs.DYHWPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getDyhwpfl() {
        return dyhwpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.DYHWPFL
     *
     * @param dyhwpfl the value for t_hjjczz_wrfhzs.DYHWPFL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setDyhwpfl(Double dyhwpfl) {
        this.dyhwpfl = dyhwpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.DYHWXS
     *
     * @return the value of t_hjjczz_wrfhzs.DYHWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getDyhwxs() {
        return dyhwxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.DYHWXS
     *
     * @param dyhwxs the value for t_hjjczz_wrfhzs.DYHWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setDyhwxs(Double dyhwxs) {
        this.dyhwxs = dyhwxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.GTFQWDQL
     *
     * @return the value of t_hjjczz_wrfhzs.GTFQWDQL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getGtfqwdql() {
        return gtfqwdql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.GTFQWDQL
     *
     * @param gtfqwdql the value for t_hjjczz_wrfhzs.GTFQWDQL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setGtfqwdql(Double gtfqwdql) {
        this.gtfqwdql = gtfqwdql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.GTFWXS
     *
     * @return the value of t_hjjczz_wrfhzs.GTFWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getGtfwxs() {
        return gtfwxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.GTFWXS
     *
     * @param gtfwxs the value for t_hjjczz_wrfhzs.GTFWXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setGtfwxs(Double gtfwxs) {
        this.gtfwxs = gtfwxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.WRFHZS
     *
     * @return the value of t_hjjczz_wrfhzs.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getWrfhzs() {
        return wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.WRFHZS
     *
     * @param wrfhzs the value for t_hjjczz_wrfhzs.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setWrfhzs(Double wrfhzs) {
        this.wrfhzs = wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.YEAR
     *
     * @return the value of t_hjjczz_wrfhzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.YEAR
     *
     * @param year the value for t_hjjczz_wrfhzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wrfhzs.TYPE
     *
     * @return the value of t_hjjczz_wrfhzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wrfhzs.TYPE
     *
     * @param type the value for t_hjjczz_wrfhzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}