package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzSwmdzs extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HLCD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hlcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hlxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hlzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HKMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hkmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HKXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hkxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.HKZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hkzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.SZYL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double szyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.SZYXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double szyxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.SZYZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double szyzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double swmdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swmdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.XH
     *
     * @return the value of t_hjjczz_swmdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.XH
     *
     * @param xh the value for t_hjjczz_swmdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.XZQMC
     *
     * @return the value of t_hjjczz_swmdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_swmdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.XZQDM
     *
     * @return the value of t_hjjczz_swmdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_swmdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.MJ
     *
     * @return the value of t_hjjczz_swmdzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.MJ
     *
     * @param mj the value for t_hjjczz_swmdzs.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HLCD
     *
     * @return the value of t_hjjczz_swmdzs.HLCD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHlcd() {
        return hlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HLCD
     *
     * @param hlcd the value for t_hjjczz_swmdzs.HLCD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHlcd(Double hlcd) {
        this.hlcd = hlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HLXS
     *
     * @return the value of t_hjjczz_swmdzs.HLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHlxs() {
        return hlxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HLXS
     *
     * @param hlxs the value for t_hjjczz_swmdzs.HLXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHlxs(Double hlxs) {
        this.hlxs = hlxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HLZS
     *
     * @return the value of t_hjjczz_swmdzs.HLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHlzs() {
        return hlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HLZS
     *
     * @param hlzs the value for t_hjjczz_swmdzs.HLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHlzs(Double hlzs) {
        this.hlzs = hlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HKMJ
     *
     * @return the value of t_hjjczz_swmdzs.HKMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHkmj() {
        return hkmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HKMJ
     *
     * @param hkmj the value for t_hjjczz_swmdzs.HKMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHkmj(Double hkmj) {
        this.hkmj = hkmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HKXS
     *
     * @return the value of t_hjjczz_swmdzs.HKXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHkxs() {
        return hkxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HKXS
     *
     * @param hkxs the value for t_hjjczz_swmdzs.HKXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHkxs(Double hkxs) {
        this.hkxs = hkxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.HKZS
     *
     * @return the value of t_hjjczz_swmdzs.HKZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHkzs() {
        return hkzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.HKZS
     *
     * @param hkzs the value for t_hjjczz_swmdzs.HKZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHkzs(Double hkzs) {
        this.hkzs = hkzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.SZYL
     *
     * @return the value of t_hjjczz_swmdzs.SZYL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSzyl() {
        return szyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.SZYL
     *
     * @param szyl the value for t_hjjczz_swmdzs.SZYL
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSzyl(Double szyl) {
        this.szyl = szyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.SZYXS
     *
     * @return the value of t_hjjczz_swmdzs.SZYXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSzyxs() {
        return szyxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.SZYXS
     *
     * @param szyxs the value for t_hjjczz_swmdzs.SZYXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSzyxs(Double szyxs) {
        this.szyxs = szyxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.SZYZS
     *
     * @return the value of t_hjjczz_swmdzs.SZYZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSzyzs() {
        return szyzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.SZYZS
     *
     * @param szyzs the value for t_hjjczz_swmdzs.SZYZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSzyzs(Double szyzs) {
        this.szyzs = szyzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.SWMDZS
     *
     * @return the value of t_hjjczz_swmdzs.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSwmdzs() {
        return swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.SWMDZS
     *
     * @param swmdzs the value for t_hjjczz_swmdzs.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSwmdzs(Double swmdzs) {
        this.swmdzs = swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.YEAR
     *
     * @return the value of t_hjjczz_swmdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.YEAR
     *
     * @param year the value for t_hjjczz_swmdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swmdzs.TYPE
     *
     * @return the value of t_hjjczz_swmdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swmdzs.TYPE
     *
     * @param type the value for t_hjjczz_swmdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}