package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzSwfdzs extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double sjzlz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double sjgyhxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double sjzlzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double swdyxzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double swfdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swfdzs
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.XH
     *
     * @return the value of t_hjjczz_swfdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.XH
     *
     * @param xh the value for t_hjjczz_swfdzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.XZQMC
     *
     * @return the value of t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.XZQDM
     *
     * @return the value of t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @return the value of t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSjzlz() {
        return sjzlz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @param sjzlz the value for t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSjzlz(Double sjzlz) {
        this.sjzlz = sjzlz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @return the value of t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSjgyhxs() {
        return sjgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @param sjgyhxs the value for t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSjgyhxs(Double sjgyhxs) {
        this.sjgyhxs = sjgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @return the value of t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSjzlzs() {
        return sjzlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @param sjzlzs the value for t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSjzlzs(Double sjzlzs) {
        this.sjzlzs = sjzlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @return the value of t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSwdyxzs() {
        return swdyxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @param swdyxzs the value for t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSwdyxzs(Double swdyxzs) {
        this.swdyxzs = swdyxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @return the value of t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSwfdzs() {
        return swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @param swfdzs the value for t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSwfdzs(Double swfdzs) {
        this.swfdzs = swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.YEAR
     *
     * @return the value of t_hjjczz_swfdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.YEAR
     *
     * @param year the value for t_hjjczz_swfdzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.TYPE
     *
     * @return the value of t_hjjczz_swfdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.TYPE
     *
     * @param type the value for t_hjjczz_swfdzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}