package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzEi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.EI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double ei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String pjjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_ei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_ei
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.XH
     *
     * @return the value of t_hjjczz_ei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.XH
     *
     * @param xh the value for t_hjjczz_ei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.XZQMC
     *
     * @return the value of t_hjjczz_ei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_ei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.XZQDM
     *
     * @return the value of t_hjjczz_ei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_ei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.EI
     *
     * @return the value of t_hjjczz_ei.EI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getEi() {
        return ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.EI
     *
     * @param ei the value for t_hjjczz_ei.EI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setEi(Double ei) {
        this.ei = ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.PJJG
     *
     * @return the value of t_hjjczz_ei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getPjjg() {
        return pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.PJJG
     *
     * @param pjjg the value for t_hjjczz_ei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setPjjg(String pjjg) {
        this.pjjg = pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.YEAR
     *
     * @return the value of t_hjjczz_ei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.YEAR
     *
     * @param year the value for t_hjjczz_ei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_ei.TYPE
     *
     * @return the value of t_hjjczz_ei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_ei.TYPE
     *
     * @param type the value for t_hjjczz_ei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}