package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzTdzyjz extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.START_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer startYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.END_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer endYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.TDLYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String tdlylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.ZYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String zylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.GD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double gd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.LD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double ld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.CD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.SY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double sy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.JSYD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double jsyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.WLY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double wly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tdzyjz.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_tdzyjz
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.START_YEAR
     *
     * @return the value of t_hjjczz_tdzyjz.START_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.START_YEAR
     *
     * @param startYear the value for t_hjjczz_tdzyjz.START_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.END_YEAR
     *
     * @return the value of t_hjjczz_tdzyjz.END_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.END_YEAR
     *
     * @param endYear the value for t_hjjczz_tdzyjz.END_YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.TDLYLX
     *
     * @return the value of t_hjjczz_tdzyjz.TDLYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getTdlylx() {
        return tdlylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.TDLYLX
     *
     * @param tdlylx the value for t_hjjczz_tdzyjz.TDLYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdlylx(String tdlylx) {
        this.tdlylx = tdlylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.ZYLX
     *
     * @return the value of t_hjjczz_tdzyjz.ZYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getZylx() {
        return zylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.ZYLX
     *
     * @param zylx the value for t_hjjczz_tdzyjz.ZYLX
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZylx(String zylx) {
        this.zylx = zylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.GD
     *
     * @return the value of t_hjjczz_tdzyjz.GD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getGd() {
        return gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.GD
     *
     * @param gd the value for t_hjjczz_tdzyjz.GD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setGd(Double gd) {
        this.gd = gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.LD
     *
     * @return the value of t_hjjczz_tdzyjz.LD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getLd() {
        return ld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.LD
     *
     * @param ld the value for t_hjjczz_tdzyjz.LD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setLd(Double ld) {
        this.ld = ld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.CD
     *
     * @return the value of t_hjjczz_tdzyjz.CD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.CD
     *
     * @param cd the value for t_hjjczz_tdzyjz.CD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setCd(Double cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.SY
     *
     * @return the value of t_hjjczz_tdzyjz.SY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSy() {
        return sy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.SY
     *
     * @param sy the value for t_hjjczz_tdzyjz.SY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSy(Double sy) {
        this.sy = sy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.JSYD
     *
     * @return the value of t_hjjczz_tdzyjz.JSYD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getJsyd() {
        return jsyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.JSYD
     *
     * @param jsyd the value for t_hjjczz_tdzyjz.JSYD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setJsyd(Double jsyd) {
        this.jsyd = jsyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.WLY
     *
     * @return the value of t_hjjczz_tdzyjz.WLY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getWly() {
        return wly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.WLY
     *
     * @param wly the value for t_hjjczz_tdzyjz.WLY
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setWly(Double wly) {
        this.wly = wly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tdzyjz.TYPE
     *
     * @return the value of t_hjjczz_tdzyjz.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tdzyjz.TYPE
     *
     * @param type the value for t_hjjczz_tdzyjz.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}