package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzSthjzlei extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double swfdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double zbfgzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double swmdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double tdxpzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double wrfhzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double sthjzkzsei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String pjjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double xymj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double hjxzzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_sthjzlei
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XH
     *
     * @return the value of t_hjjczz_sthjzlei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XH
     *
     * @param xh the value for t_hjjczz_sthjzlei.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @return the value of t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @return the value of t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @return the value of t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSwfdzs() {
        return swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @param swfdzs the value for t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSwfdzs(Double swfdzs) {
        this.swfdzs = swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @return the value of t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getZbfgzs() {
        return zbfgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @param zbfgzs the value for t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZbfgzs(Double zbfgzs) {
        this.zbfgzs = zbfgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @return the value of t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSwmdzs() {
        return swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @param swmdzs the value for t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSwmdzs(Double swmdzs) {
        this.swmdzs = swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @return the value of t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getTdxpzs() {
        return tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @param tdxpzs the value for t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdxpzs(Double tdxpzs) {
        this.tdxpzs = tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @return the value of t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getWrfhzs() {
        return wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @param wrfhzs the value for t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setWrfhzs(Double wrfhzs) {
        this.wrfhzs = wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @return the value of t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getSthjzkzsei() {
        return sthjzkzsei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @param sthjzkzsei the value for t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSthjzkzsei(Double sthjzkzsei) {
        this.sthjzkzsei = sthjzkzsei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.PJJG
     *
     * @return the value of t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getPjjg() {
        return pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.PJJG
     *
     * @param pjjg the value for t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setPjjg(String pjjg) {
        this.pjjg = pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @return the value of t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getXymj() {
        return xymj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @param xymj the value for t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXymj(Double xymj) {
        this.xymj = xymj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.HJXZZS
     *
     * @return the value of t_hjjczz_sthjzlei.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getHjxzzs() {
        return hjxzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.HJXZZS
     *
     * @param hjxzzs the value for t_hjjczz_sthjzlei.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHjxzzs(Double hjxzzs) {
        this.hjxzzs = hjxzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.YEAR
     *
     * @return the value of t_hjjczz_sthjzlei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.YEAR
     *
     * @param year the value for t_hjjczz_sthjzlei.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.TYPE
     *
     * @return the value of t_hjjczz_sthjzlei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.TYPE
     *
     * @param type the value for t_hjjczz_sthjzlei.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}