package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzHjxzzs extends  ObjHandle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.TDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer tdhjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.ZDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer zdhjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.JDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer jdhjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.YBHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer ybhjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.HJWR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer hjwr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.STPH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer stph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.STHJWFAJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer sthjwfaj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.BNRQYXPFW
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer bnrqyxpfw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String hjxzzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_hjxzzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.XH
     *
     * @return the value of t_hjjczz_hjxzzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.XH
     *
     * @param xh the value for t_hjjczz_hjxzzs.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.XZQMC
     *
     * @return the value of t_hjjczz_hjxzzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_hjxzzs.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.XZQDM
     *
     * @return the value of t_hjjczz_hjxzzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_hjxzzs.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.TDHJSJ
     *
     * @return the value of t_hjjczz_hjxzzs.TDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getTdhjsj() {
        return tdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.TDHJSJ
     *
     * @param tdhjsj the value for t_hjjczz_hjxzzs.TDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTdhjsj(Integer tdhjsj) {
        this.tdhjsj = tdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.ZDHJSJ
     *
     * @return the value of t_hjjczz_hjxzzs.ZDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getZdhjsj() {
        return zdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.ZDHJSJ
     *
     * @param zdhjsj the value for t_hjjczz_hjxzzs.ZDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setZdhjsj(Integer zdhjsj) {
        this.zdhjsj = zdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.JDHJSJ
     *
     * @return the value of t_hjjczz_hjxzzs.JDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getJdhjsj() {
        return jdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.JDHJSJ
     *
     * @param jdhjsj the value for t_hjjczz_hjxzzs.JDHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setJdhjsj(Integer jdhjsj) {
        this.jdhjsj = jdhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.YBHJSJ
     *
     * @return the value of t_hjjczz_hjxzzs.YBHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getYbhjsj() {
        return ybhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.YBHJSJ
     *
     * @param ybhjsj the value for t_hjjczz_hjxzzs.YBHJSJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYbhjsj(Integer ybhjsj) {
        this.ybhjsj = ybhjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.HJWR
     *
     * @return the value of t_hjjczz_hjxzzs.HJWR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getHjwr() {
        return hjwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.HJWR
     *
     * @param hjwr the value for t_hjjczz_hjxzzs.HJWR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHjwr(Integer hjwr) {
        this.hjwr = hjwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.STPH
     *
     * @return the value of t_hjjczz_hjxzzs.STPH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getStph() {
        return stph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.STPH
     *
     * @param stph the value for t_hjjczz_hjxzzs.STPH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setStph(Integer stph) {
        this.stph = stph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.STHJWFAJ
     *
     * @return the value of t_hjjczz_hjxzzs.STHJWFAJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getSthjwfaj() {
        return sthjwfaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.STHJWFAJ
     *
     * @param sthjwfaj the value for t_hjjczz_hjxzzs.STHJWFAJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setSthjwfaj(Integer sthjwfaj) {
        this.sthjwfaj = sthjwfaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.BNRQYXPFW
     *
     * @return the value of t_hjjczz_hjxzzs.BNRQYXPFW
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getBnrqyxpfw() {
        return bnrqyxpfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.BNRQYXPFW
     *
     * @param bnrqyxpfw the value for t_hjjczz_hjxzzs.BNRQYXPFW
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setBnrqyxpfw(Integer bnrqyxpfw) {
        this.bnrqyxpfw = bnrqyxpfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.HJXZZS
     *
     * @return the value of t_hjjczz_hjxzzs.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getHjxzzs() {
        return hjxzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.HJXZZS
     *
     * @param hjxzzs the value for t_hjjczz_hjxzzs.HJXZZS
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setHjxzzs(String hjxzzs) {
        this.hjxzzs = hjxzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.YEAR
     *
     * @return the value of t_hjjczz_hjxzzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.YEAR
     *
     * @param year the value for t_hjjczz_hjxzzs.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_hjxzzs.TYPE
     *
     * @return the value of t_hjjczz_hjxzzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_hjxzzs.TYPE
     *
     * @param type the value for t_hjjczz_hjxzzs.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}