package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzRktj implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.RK
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double rk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.RKZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String rkzb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_rktj.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_rktj
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.XH
     *
     * @return the value of t_hjjczz_rktj.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.XH
     *
     * @param xh the value for t_hjjczz_rktj.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.XZQMC
     *
     * @return the value of t_hjjczz_rktj.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_rktj.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.XZQDM
     *
     * @return the value of t_hjjczz_rktj.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_rktj.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.RK
     *
     * @return the value of t_hjjczz_rktj.RK
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getRk() {
        return rk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.RK
     *
     * @param rk the value for t_hjjczz_rktj.RK
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setRk(Double rk) {
        this.rk = rk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.RKZB
     *
     * @return the value of t_hjjczz_rktj.RKZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getRkzb() {
        return rkzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.RKZB
     *
     * @param rkzb the value for t_hjjczz_rktj.RKZB
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setRkzb(String rkzb) {
        this.rkzb = rkzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.YEAR
     *
     * @return the value of t_hjjczz_rktj.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.YEAR
     *
     * @param year the value for t_hjjczz_rktj.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_rktj.TYPE
     *
     * @return the value of t_hjjczz_rktj.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_rktj.TYPE
     *
     * @param type the value for t_hjjczz_rktj.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}