package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzWlyddpgd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.WLYDDPGD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Double wlyddpgd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_wlyddpgd.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_wlyddpgd
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.XH
     *
     * @return the value of t_hjjczz_wlyddpgd.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.XH
     *
     * @param xh the value for t_hjjczz_wlyddpgd.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.XZQMC
     *
     * @return the value of t_hjjczz_wlyddpgd.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_wlyddpgd.XZQMC
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.XZQDM
     *
     * @return the value of t_hjjczz_wlyddpgd.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_wlyddpgd.XZQDM
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.MJ
     *
     * @return the value of t_hjjczz_wlyddpgd.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.MJ
     *
     * @param mj the value for t_hjjczz_wlyddpgd.MJ
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.WLYDDPGD
     *
     * @return the value of t_hjjczz_wlyddpgd.WLYDDPGD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Double getWlyddpgd() {
        return wlyddpgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.WLYDDPGD
     *
     * @param wlyddpgd the value for t_hjjczz_wlyddpgd.WLYDDPGD
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setWlyddpgd(Double wlyddpgd) {
        this.wlyddpgd = wlyddpgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.YEAR
     *
     * @return the value of t_hjjczz_wlyddpgd.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.YEAR
     *
     * @param year the value for t_hjjczz_wlyddpgd.YEAR
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_wlyddpgd.TYPE
     *
     * @return the value of t_hjjczz_wlyddpgd.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_wlyddpgd.TYPE
     *
     * @param type the value for t_hjjczz_wlyddpgd.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}