package com.sxxa.hjjczz.entity;

import java.io.Serializable;

public class THjjczzTablelist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tablelist.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String tablenameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String tablenameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_tablelist.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_tablelist
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tablelist.XH
     *
     * @return the value of t_hjjczz_tablelist.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tablelist.XH
     *
     * @param xh the value for t_hjjczz_tablelist.XH
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tablelist.TABLENAME_EN
     *
     * @return the value of t_hjjczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getTablenameEn() {
        return tablenameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tablelist.TABLENAME_EN
     *
     * @param tablenameEn the value for t_hjjczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTablenameEn(String tablenameEn) {
        this.tablenameEn = tablenameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tablelist.TABLENAME_CN
     *
     * @return the value of t_hjjczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getTablenameCn() {
        return tablenameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tablelist.TABLENAME_CN
     *
     * @param tablenameCn the value for t_hjjczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setTablenameCn(String tablenameCn) {
        this.tablenameCn = tablenameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_tablelist.TYPE
     *
     * @return the value of t_hjjczz_tablelist.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_tablelist.TYPE
     *
     * @param type the value for t_hjjczz_tablelist.TYPE
     *
     * @mbggenerated Thu Mar 04 17:03:32 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}